[tool.black]
line-length = 88
target-version = ["py39"]

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.9"
ignore_missing_imports = true
strict = true

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
